### ISSUE TITLE
怎么获取DAG里的每个task的执行状态？

### ISSUE THREAD

**Issue by felixZ828** [ShiningRush/fastflow#10]
尝试获取Dag里task的状态，

	dag, err := mod.GetStore().GetDag("test-dag")

	if err != nil {
		panic(err)
	}

	for _, task := range dag.Tasks{
		println("============== ", task.ActionName, task.GetStatus())
	}

但是看实现里 task.GetStatus()返回的是空字符串

      // GetStatus
      func (t *Task) GetStatus() TaskInstanceStatus {
	      return ""
      }

看源码里有TaskInstance可以获取状态

      // GetStatus
      func (t *TaskInstance) GetStatus() TaskInstanceStatus {
	      return t.Status
      }

**这个TaskInstance怎么能获取到进而再获取其执行状态？**

**Comment by ShiningRush** [comment]
Dag是模板，只有运行的实例才具备状态，因此你应该使用
```
dag, err := mod.GetStore().GetDagInstance("your-daginstance-id")
```

**Comment by qifei717** [comment]
获取到DagInstance后，怎么获取TaskInstance，是想获取TaskInstance的status

**Comment by ShiningRush** [comment]
你可以按照你最开始的思路去遍历获取到TaskInstance就好，不过这种方式不常见，你也可以通过 `ListTaskInstance` 与 `GetTaskIns` 方法去获取。
另外一般都是在Action当中获取TaskInstance的状态，通常不建议程序通过 `Store` 去干涉fastflow的执行状态，可以描述下你的背景需求吗

**Comment by qifei717** [comment]
刚开始也是在action中获取TaskInstance的状态，这个怎么获取？没有找到方法。
通过 ListTaskInstance 与 GetTaskIns 方法去获取这个有示例代码吗？
背景：就是工作流执行的时候，想看到工作流执行到哪个task了，并且当前每个task的状态是什么，最终需要把状态展示在web页面上

**Comment by ShiningRush** [comment]
> 就是工作流执行的时候，想看到工作流执行到哪个task了，并且当前每个task的状态是什么，最终需要把状态展示在web页面上

get ，我们在内部有类似的功能，可以直接使用 `ListTaskInstance(dagId)` 获取任务实例后返回到前端即可，前端根据TaskList去渲染一个DAG执行树就行了，大概这个样子
<img width="1740" alt="image" src="https://user-images.githubusercontent.com/24238012/199728335-0a635792-0163-4cc0-986f-391f2e4d70af.png">

旁边的参数列表是基于Action的Paramter动态生成的

**Comment by cplinux** [comment]
> > 就是工作流执行的时候，想看到工作流执行到哪个task了，并且当前每个task的状态是什么，最终需要把状态展示在web页面上
> 
> get ，我们在内部有类似的功能，可以直接使用 `ListTaskInstance(dagId)` 获取任务实例后返回到前端即可，前端根据TaskList去渲染一个DAG执行树就行了，大概这个样子 <img alt="图片" width="1740" src="https://user-images.githubusercontent.com/24238012/199728335-0a635792-0163-4cc0-986f-391f2e4d70af.png">
> 
> 旁边的参数列表是基于Action的Paramter动态生成的

你好，前端这个流程展示是用的哪个库啊

**Comment by ShiningRush** [comment]
> > > 就是工作流执行的时候，想看到工作流执行到哪个task了，并且当前每个task的状态是什么，最终需要把状态展示在web页面上
> > 
> > 
> > get ，我们在内部有类似的功能，可以直接使用 `ListTaskInstance(dagId)` 获取任务实例后返回到前端即可，前端根据TaskList去渲染一个DAG执行树就行了，大概这个样子 <img alt="图片" width="1740" src="https://user-images.githubusercontent.com/24238012/199728335-0a635792-0163-4cc0-986f-391f2e4d70af.png">
> > 旁边的参数列表是基于Action的Paramter动态生成的
> 
> 你好，前端这个流程展示是用的哪个库啊

这个我不太记得了，得问问前端同学，我们当时前端是vue，所以你搜索下vue + dag 应该能发现一些相关线索
