### ISSUE TITLE
咨询：现有模型支持进程重启恢复继续执行吗

### ISSUE THREAD

**Issue by fm2022aa** [ShiningRush/fastflow#15]
1、例如一个长任务，executor跑的中途重启了，起来后支持自动继续执行吗

**Comment by ShiningRush** [comment]
看执行阶段：
- `RunBefore`, `RunAfter`: 在运行中宕机，重启后会重新执行
- `Run`: 不会，该动作永远只会运行一次，如果上次过程尚未完成，重启后会判定失败。

**Comment by fm2022aa** [comment]
ok, thanks
