### ISSUE TITLE
在ctx中可以取到当前任务信息吗

### ISSUE THREAD

**Issue by kangarooxin** [ShiningRush/fastflow#19]
在 Run(ctx run.ExecuteContext, params interface{}) 的 ctx 中可以取到当前任务相关信息吗

dagId 
dagInsId 
taskId ： 节点ID

或者如何能获取到呢

**Comment by ShiningRush** [comment]
可以使用 `mod.GetStore().GetTaskIns()` 来获取，参考 #10 ,不过通常来说不建议在action去获取状态，背景是怎样的呢

**Comment by kangarooxin** [comment]
打印log的时候，输出一些信息

**Comment by kangarooxin** [comment]
> 可以使用 `mod.GetStore().GetTaskIns()` 来获取，参考 #10 ,不过通常来说不建议在action去获取状态，背景是怎样的呢

这个接口需要taskIns，这个在action内部能取到吗？

**Comment by ShiningRush** [comment]
看上去是合理的诉求，我觉得可以把运行时的DagIInstane和TaskInstance都注入到Context。
我51可以写个PR，也欢迎你直接提PR。

**Comment by ShiningRush** [comment]
@kangarooxin 已经在 #20 中支持，现在你可以在action中使用如下语句获取
```go
func Run(ctx ExecuteContext, params interface{}) error {
    taskIns, ok := entity.CtxRunningTaskIns(ctx.Context())
}

```

**Comment by kangarooxin** [comment]
> @kangarooxin 已经在 #20 中支持，现在你可以在action中使用如下语句获取
> 
> ```go
> func Run(ctx ExecuteContext, params interface{}) error {
>     taskIns, ok := entity.CtxRunningTaskIns(ctx.Context())
> }
> ```

好的，辛苦
