### ISSUE TITLE
重试状态性能优化

### ISSUE THREAD

**Issue by philhuan** [ShiningRush/fastflow#23]
https://github.com/ShiningRush/fastflow/blob/master/pkg/entity/task.go#L295

这里如果是重试，状态转为init后，直接退出了，然后等待parser继续遍历并且重新提交，这里为什么不直接在 Executor 里面继续运行呢，除了要重新渲染一遍参数，还有其他原因吗

**Comment by ShiningRush** [comment]
主要是从设计上确保流程一致性，如果直接进入到Executor，假设之后对Action的执行添加了别的hook，可能导致霰弹式修改
