### ISSUE TITLE
Keeper和Store对于fastflow是必须的么？有没有standalone形式的实现方案？

### ISSUE THREAD

**Issue by fengjian1993** [ShiningRush/fastflow#26]

**Comment by ShiningRush** [comment]
Keeper，Store是所有节点（Leader or Worker）的核心模块。前者用于保持心跳、选主和分布式锁等等，后者用于隔离解耦的存储，如果去除的话，fastflow就只剩下了Dag树的解析和执行，我不确定这部分能力在什么场景需要Standalone的方案。

或许你想了解的是否为——Leader和Worker是否可以独立部署？感觉这个形式更有价值

**Comment by fengjian1993** [comment]
> Keeper，Store是所有节点（Leader or Worker）的核心模块。前者用于保持心跳、选主和分布式锁等等，后者用于隔离解耦的存储，如果去除的话，fastflow就只剩下了Dag树的解析和执行，我不确定这部分能力在什么场景需要Standalone的方案。
> 
> 或许你想了解的是否为——Leader和Worker是否可以独立部署？感觉这个形式更有价值

我需要一个dag树的解析和执行，然后扩展一些执行插件什么的。感觉更像是增强版的模板模式，用来改造现有按顺序堆砌的代码

**Comment by ShiningRush** [comment]
奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。
因为它们都是依赖的接口而不是具体的引用。
比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解

**Comment by fengjian1993** [comment]
> 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解

看不太懂 可以写一个单元测试或者伪代码看一下么 谢谢

**Comment by fengjian1993** [comment]
> 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解

空实现keeper和store是否可行？

**Comment by ShiningRush** [comment]
> > 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解
> 
> 看不太懂 可以写一个单元测试或者伪代码看一下么 谢谢

demo可能得晚点给你了，这几天公司事情比较多

**Comment by ShiningRush** [comment]
> > 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解
> 
> 空实现keeper和store是否可行？

空store是可行的，空keeper不太行，因为涉及到ID生成和Worker获取，如果你不需要任务派发，只要Dag执行的话，只要实现ID生成应该就行了

**Comment by fengjian1993** [comment]
> > > 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解
> > 
> > 
> > 空实现keeper和store是否可行？
> 
> 空store是可行的，空keeper不太行，因为涉及到ID生成和Worker获取，如果你不需要任务派发，只要Dag执行的话，只要实现ID生成应该就行了

实现了一下 不知道parser.go的goWorker函数的queue里面的taskIns是从哪里push的, 我的mod.GetCommander().RunDag好像无效

**Comment by ShiningRush** [comment]
> > > > 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解
> > > 
> > > 
> > > 空实现keeper和store是否可行？
> > 
> > 
> > 空store是可行的，空keeper不太行，因为涉及到ID生成和Worker获取，如果你不需要任务派发，只要Dag执行的话，只要实现ID生成应该就行了
> 
> 实现了一下 不知道parser.go的goWorker函数的queue里面的taskIns是从哪里push的, 我的mod.GetCommander().RunDag好像无效

hi，很抱歉最近事情比较多，回复慢了，这里面的dag instance是从GetStore().ListDagInstance 获取而来的哦，在启动的时候会默认拉取正在运行的DagInstance运行。

**Comment by mingmingshiliyu** [comment]
> > > > 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解
> > > 
> > > 
> > > 空实现keeper和store是否可行？
> > 
> > 
> > 空store是可行的，空keeper不太行，因为涉及到ID生成和Worker获取，如果你不需要任务派发，只要Dag执行的话，只要实现ID生成应该就行了
> 
> 实现了一下 不知道parser.go的goWorker函数的queue里面的taskIns是从哪里push的, 我的mod.GetCommander().RunDag好像无效

老哥mock成功了么,关于去除mongodb的依赖

**Comment by fengjian1993** [comment]
> > > > > 奥，那你可以直接引用Parser, Executor模块就好，虽然它们会依赖Keeper, Store，但是你完全可以自己Mock一份实现设置就好。 因为它们都是依赖的接口而不是具体的引用。 比如实现一个空实现的Store，然后固定Key的Keeper；如果再细一点你甚至可以只引用DagBuild相关的核心代码，不过需要你对里面的实现比较了解
> > > > 
> > > > 
> > > > 空实现keeper和store是否可行？
> > > 
> > > 
> > > 空store是可行的，空keeper不太行，因为涉及到ID生成和Worker获取，如果你不需要任务派发，只要Dag执行的话，只要实现ID生成应该就行了
> > 
> > 
> > 实现了一下 不知道parser.go的goWorker函数的queue里面的taskIns是从哪里push的, 我的mod.GetCommander().RunDag好像无效
> 
> 老哥mock成功了么,关于去除mongodb的依赖

keeper本地模式实现很简单 store实现麻烦一点 基本所有的方法都要重新实现 但是都是围绕syncmap就行了 主要就是dag，task 和 taskinstance。另外需要改一点源码 看看debug就行了
