### ISSUE TITLE
通过fastflow 能否实现审批流

### ISSUE THREAD

**Issue by bugKai001** [ShiningRush/fastflow#30]
手动去控制流程的通过、拒绝

**Comment by ShiningRush** [comment]
可以，通过PreCheck block节点的执行，然后通过API调用Commander的Continue的来恢复Task的执行

**Comment by bugKai001** [comment]
> 可以，通过PreCheck block节点的执行，然后通过API调用Commander的Continue的来恢复Task的执行

好的，谢谢，但是如果去实现撤回功能呢

**Comment by ShiningRush** [comment]
撤回功能可以直接CancelTask就好，但是如果在审批前发生了副作用了，就还需要发起一个Rollback的流程，目前fastflow暂时不支持rollback

**Comment by yannan** [comment]
> 可以，通过PreCheck block节点的执行，然后通过API调用Commander的Continue的来恢复Task的执行

想请教下，怎么让block的节点恢复执行？

**Comment by ShiningRush** [comment]
> > 可以，通过PreCheck block节点的执行，然后通过API调用Commander的Continue的来恢复Task的执行
> 
> 想请教下，怎么让block的节点恢复执行？

需要调用`Commander`的Continue指令，不过我看了，这个功能尚未同步到开源版本，我晚点实现下
