### ISSUE TITLE
如何在Action的Run方法体内获取当前的Task Instance ID的元信息呢？

### ISSUE THREAD

**Issue by HtcOrange** [ShiningRush/fastflow#32]
假设当前存在某种定制的跳过场景，外部想控制某个task进行跳过

设置sharedata中要跳过的taskinstance的skip字段为true，理论上在action的runafter方法体内轮询这个字段即可。但我应该如何在逻辑中确认当前正在运行的action属于具体的哪一个taskinstance呢？似乎并没有找到通过run.ExecuteContext获取当前运行时taskinstance信息的接口啊

**Comment by ShiningRush** [comment]
Task的`PreCheck`具备跳过的能力，不需要在Action编码实现时去设置跳过的，这个满足你的要求吗

**Comment by ShiningRush** [comment]
hi, 该issue超过一个月没有回复先关闭了，如果有疑问可以重新Reopen
