### ISSUE TITLE
发现个问题,项目启动的时候register了结构体,并调用fastflow.init,然后在接口中构造dag,调用run方法,但我发现会出现actionName运行2次的情况,或者多次运行之后出现2023/10/09 22:52:18 error: parser get some error%!(EXTRA string=module, string=parser, string=err, *fmt.wrapError=worker do failed: dag instance[482065678661058561] does not found task tree)

### ISSUE THREAD

**Issue by mingmingshiliyu** [ShiningRush/fastflow#38]
使用的是项目启动的时候注册的结构体作为action,没有在每次调用的时候重复注册

**Comment by ShiningRush** [comment]
这里的错误信息格式看起来有点奇怪，我已经提了一个PR修复了。
但是原始错误
`dag instance[482065678661058561] does not found task tree`
这个的成因是因为在没有解析任务树之前就往队列中扔了`TaskInstance`，看起来是不规范的使用方法导致，可以贴下你的代码

**Comment by mingmingshiliyu** [comment]
> 这里的错误信息格式看起来有点奇怪，我已经提了一个PR修复了。
> 但是原始错误
> `dag instance[482065678661058561] does not found task tree`
> 这个的成因是因为在没有解析任务树之前就往队列中扔了`TaskInstance`，看起来是不规范的使用方法导致，可以贴下你的代码

<img width="759" alt="image" src="https://github.com/ShiningRush/fastflow/assets/143821597/2f6b46bb-f26b-4c45-bbd2-eb6497371e9d">
启动的时候注册printaction,
调用接口的时候执行fastflow.init
<img width="740" alt="image" src="https://github.com/ShiningRush/fastflow/assets/143821597/6a7fc263-9c67-48a7-b3db-e19f9a2792bf">
<img width="749" alt="image" src="https://github.com/ShiningRush/fastflow/assets/143821597/acc0b216-03a3-4fd4-87bd-9bc569be19b1">
执行dag.run
<img width="654" alt="image" src="https://github.com/ShiningRush/fastflow/assets/143821597/31324c1f-5231-46ef-8647-9b42bf6a4e1f">

<img width="794" alt="image" src="https://github.com/ShiningRush/fastflow/assets/143821597/70575b2a-16a1-4d39-be73-5784fc3e9a26">

**Comment by mingmingshiliyu** [comment]
> 这里的错误信息格式看起来有点奇怪，我已经提了一个PR修复了。
> 但是原始错误
> `dag instance[482065678661058561] does not found task tree`
> 这个的成因是因为在没有解析任务树之前就往队列中扔了`TaskInstance`，看起来是不规范的使用方法导致，可以贴下你的代码

代码有问题么

**Comment by ShiningRush** [comment]
暂时从代码上看出问题，请问现在仍然存在吗
