### ISSUE TITLE
[Feature] 可以提供UI吗

### ISSUE THREAD

**Issue by etherealiy** [ShiningRush/fastflow#40]
可以像goflow或者airflow一样提供简单的UI吗

**Comment by gaoshi1115** [comment]
同问

**Comment by ShiningRush** [comment]
hi, fastflow定位是一个`框架`而并非一个`可以直接部署的项目`。
`框架`的优点在于可以直接结合到历史项目中，可控性也更强，缺点是无法开箱即用，直接部署，没有API，所以对应的UI也无从谈起。
当然我们完全可以使用 `fastflow`作为core，另起一个项目， 开发一个类似airflow可直接部署的任务引擎，就像 `fosite` 和`hydra`的关系一样。
之前是有计划来做这件事情的，但是由于后面的一些工作变动，工作变得繁忙了起来，业务时间难以支撑这么大的投入，所以一直没开展。

**Comment by Zephyrus-cyber** [comment]
期待后续会提供这样的功能～

**Comment by ShiningRush** [comment]
> 期待后续会提供这样的功能～

感谢你的关注，如果你们有这样的诉求，也可以一起共建起新的项目
