### ISSUE TITLE
watchDagInsCmd线程处理continue cmd异常导致task在Precheck时block状态无法放开

### ISSUE THREAD

**Issue by lxn3642** [ShiningRush/fastflow#46]
parseCmd：
![WechatIMG6450](https://github.com/ShiningRush/fastflow/assets/68902480/83ad93d3-55a6-4a6d-ae02-031a888349b0)

precheck逻辑：
![image](https://github.com/ShiningRush/fastflow/assets/68902480/42770823-a5bf-48eb-a722-9e76fd25a82e)

![image](https://github.com/ShiningRush/fastflow/assets/68902480/dd73f5be-78ef-41d2-ad1d-2724f0608c01)

综上：
watchDagInsCmd线程在处理continue命令时，针对precheck阻塞场景，无法使任务继续执行，请作者大大看下~

![image](https://github.com/ShiningRush/fastflow/assets/68902480/0adfe304-2b2c-43cb-9c1d-79fda90032bb)
本地修改后可正常处理该场景

**Comment by lxn3642** [comment]
另一个推动流程的方法就是在执行continue命令前，手动update dag实例用于阻塞该任务的变量，该方法貌似没有封装，需要自己写

**Comment by ShiningRush** [comment]
感谢反馈，我现在看看

**Comment by ShiningRush** [comment]
hi, 我已经在#48 修复了该问题，这里对于需要Continue的Task其实我们不应该再次block。目前这个判断做的比较粗糙，如果存在多个block条件的话，可能还需要把上次造成Block的PreCheckName给记录下来，否则会导致其他Block的PreCheck也没法执行，不过我们先这样吧，等有需求再补充

**Comment by lxn3642** [comment]
感谢更新，continue 命令在该场景下可以正常运行了
