### ISSUE TITLE
根据示例使用ShareData对象的Set()方法未将数据持久化

### ISSUE THREAD

**Issue by lxn3642** [ShiningRush/fastflow#47]
在action中设置变量，未自动将数据持久化到mongo，详细如图：
<img width="895" alt="image" src="https://github.com/ShiningRush/fastflow/assets/68902480/c806a762-8ce8-4a3d-9e33-d3a28471d78c">

<img width="777" alt="image" src="https://github.com/ShiningRush/fastflow/assets/68902480/d7b11c0b-64d7-49fb-9f92-8ca67a7267e5">

<img width="933" alt="image" src="https://github.com/ShiningRush/fastflow/assets/68902480/2bce83cc-5264-46f4-b611-7ff8aadd9abf">

**Comment by ShiningRush** [comment]
有错误日志吗，理论上Set成功后是立马落库的

**Comment by lxn3642** [comment]
没有日志，可能是我有update操作给覆盖了，目前未复现持久化失败问题
