### ISSUE TITLE
询问：异步的task怎么搞比较好

### ISSUE THREAD

**Issue by fm2022aa** [ShiningRush/fastflow#5]
比如一个任务是要提工单让人审批，审批完后workflow继续。

**Comment by ShiningRush** [comment]
异步任务的推荐方式是在Action的Run中发起任务，然后在RunAfter中轮询检测任务状态。

**Comment by fm2022aa** [comment]
> 异步任务的推荐方式是在Action的Run中发起任务，然后在RunAfter中轮询检测任务状态。

thanks， i'd have a try.

**Comment by ShiningRush** [comment]
I close the issue now, you can reopen if you have any problems in future
