### ISSUE TITLE
能支持流式执行任务吗

### ISSUE THREAD

**Issue by akkuman** [ShiningRush/fastflow#55]
在平常写shell脚本过程中，管道通常是读取一行，然后管道符后面的程序就开始用这一行作为输入开始执行了

看了下readme，好像不支持这种流式执行的任务?

**Comment by ShiningRush** [comment]
如果直接复用fastflow的dag执行机制，后节点的执行确实是只能等待前置节点完成的，不过你可以将两个节点并行化，然后在父节点去分配通信的pipe or 内存块，这样可以实现两个任务节点的流式执行

**Comment by akkuman** [comment]
看了下，一个dag好像是由一个worker来进行执行，那这样应该也可以。
我自己的实际场景可能更偏向不同的task有不同的负载（所以不同的task有不同的机器节点），一个dag由分布式节点协同处理完成。

仔细看了下，发现和这个项目的面向场景还是有不同😂

**Comment by ShiningRush** [comment]
嗯嗯，好的，你可以再评估下。不过就我参与过众多任务引擎来看，基本上很少把task设计得很重，任务引擎一般只负责编排，而把重计算的抽成一个集群，把task节点转换为远程调用，这样更容易维护和扩展
