### ISSUE TITLE
请问如何在不重启fastflow的情况下动态的增加dag

### ISSUE THREAD

**Issue by AHHH32** [ShiningRush/fastflow#60]
我想通过读取yaml的方式动态的往数据库中写入dag，有没有相关接口。或者有没有其他方式实现

**Comment by ShiningRush** [comment]
你可以自己实现一个接口把yaml反序列化为Dag对象，然后调用Store模块持久化即可

**Comment by AHHH32** [comment]
> 你可以自己实现一个接口把yaml反序列化为Dag对象，然后调用Store模块持久化即可
