### ISSUE TITLE
question: DAG 任务支持取消与回滚吗？

### ISSUE THREAD

**Issue by beihai0xff** [ShiningRush/fastflow#7]
如题，一个 DAG 内的任务，支持任务支持取消与回滚吗？
例如 DAG 执行到某个中间步骤，此时前端调用取消任务的 API，是否支持将正在执行中（Running）的任务取消，并回滚已经执行完成的（success）任务？

**Comment by ShiningRush** [comment]
- 可以通过commander执行取消指令，fastflow会通知正在执行的实例通过 context 通知(action需要处理context的cancel信号)。
- 目前不支持回滚这个动作，对于一些必须强一致的场景，我们是通过启动一个反向补偿的dag来完成的，这是由于在action中一般都是比较复杂难以回滚的业务操作，所以我们期望通过事前检查、过程中人工干涉+重试+action幂等，来尽量以forward的形式完成最终一致。
我们也曾考虑过在action中支持定义一些反操作来进行回滚，但是综合比较下载，觉得适用场景较少所以没有支持，如果你们是一个强需求，欢迎一起讨论背景和方案

**Comment by beihai0xff** [comment]
> * 可以通过commander执行取消指令，fastflow会通知正在执行的实例通过 context 通知(action需要处理context的cancel信号)。

了解了。但是我们的应用场景 Worker 可能是 Golang 程序也可能是 Python 程序，Golang 程序用 context 是可以捕捉到 cancel 信号来执行退出逻辑，但是 Python 程序还没有比较好的解决方式，目前只能强制 kill 协程/进程（或者自己实现一个信号通知机制）。还有一个点是任务执行过程中可能会启动子进程，例如执行 shell 脚本，目前也没有比较好的方式终结子进程。
> * 目前不支持回滚这个动作，对于一些必须强一致的场景，我们是通过启动一个反向补偿的dag来完成的，这是由于在action中一般都是比较复杂难以回滚的业务操作，所以我们期望通过事前检查、过程中人工干涉+重试+action幂等，来尽量以forward的形式完成最终一致。

我们目前也是反向补偿的思路，但是由于依赖于 [celery]( https://github.com/celery/celery) 这个框架，不太方便做扩展...

**Comment by beihai0xff** [comment]
> * 可以通过commander执行取消指令，fastflow会通知正在执行的实例通过 context 通知(action需要处理context的cancel信号)。

了解了。但是我们的应用场景 Worker 可能是 Golang 程序也可能是 Python 程序，Golang 程序用 context 是可以捕捉到 cancel 信号来执行退出逻辑，但是 Python 程序还没有比较好的解决方式，目前只能强制 kill 协程/进程（或者自己实现一个信号通知机制）。还有一个点是任务执行过程中可能会启动子进程，例如执行 shell 脚本，kill。
> * 目前不支持回滚这个动作，对于一些必须强一致的场景，我们是通过启动一个反向补偿的dag来完成的，这是由于在action中一般都是比较复杂难以回滚的业务操作，所以我们期望通过事前检查、过程中人工干涉+重试+action幂等，来尽量以forward的形式完成最终一致。

我们目前也是反向补偿的思路，但是由于依赖于 [celery]( https://github.com/celery/celery) 这个框架，不太方便做扩展...

**Comment by ShiningRush** [comment]
> 但是 Python 程序还没有比较好的解决方式，目前只能强制 kill 协程/进程

我们还没自研fastflow前用的是airflow，当时就是不能取消的，只能等它执行完，而且一个task节点一个进程，在高并发的场景消耗资源太大了。
从我的角度看，如果你们依然要保留python的部分，建议把执行单位迁移到pod，这样至少更容易跟踪和控制(前提是你们是在k8s环境)，不然考虑全部迁移到golang，控制成本会更低一些。

> 我们目前也是反向补偿的思路

我们反向补偿的例子非常少，绝大多数case还是以推动任务执行成功来思考方案的(比如更严格的条件审查、更长时间地占有临界资源等)，补偿这个事情维护和实现成本都比较高，不到万不得已最好不要尝试。

**Comment by beihai0xff** [comment]
> 从我的角度看，如果你们依然要保留python的部分，建议把执行单位迁移到pod，这样至少更容易跟踪和控制(前提是你们是在k8s环境)，不然考虑全部迁移到golang，控制成本会更低一些。

这一套系统已经运行五六年了，积累了大量的 Python 任务脚本，全部迁移到 Golang 的成本高昂，而且部分服务目前还是使用 python 开发的。执行单元容器化的方式改造成本也很高（如果能抛弃依赖的 celery 还是有操作空间的）

> 我们反向补偿的例子非常少，绝大多数case还是以推动任务执行成功来思考方案的(比如更严格的条件审查、更长时间地占有临界资源等)，补偿这个事情维护和实现成本都比较高，不到万不得已最好不要尝试。
嗯，分布式事务的开发与维护成本都太高了，我也看了一下 [dtm](https://github.com/dtm-labs/dtm)的思路，实现成本确实繁琐
